export enum ActionTypes {
    ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
    CHANGE_QUANTITY = "CHANGE_QUANTITY",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    CHANGE_PAYMENT_MODE = "CHANGE_PAYMENT_MODE",
    UPDATE_ADDRESS = "UPDATE_ADDRESS",
    CLEAR_CART = "CLEAR_CART"
}